config/routes.rb
Rails.application.routes.draw do
  resources :person_affiliations
  resources :person_locations
  resources :locations
  resources :affiliations
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/person_affiliation.rb
class PersonAffiliation < ApplicationRecord
  belongs_to :person
  belongs_to :affiliation
end

app/controllers/person_affiliations_controller.rb
class PersonAffiliationsController < ApplicationController
  before_action :set_person_affiliation, only: %i[ show edit update destroy ]

  # GET /person_affiliations or /person_affiliations.json
  def index
    @person_affiliations = PersonAffiliation.all
  end

  # GET /person_affiliations/1 or /person_affiliations/1.json
  def show
  end

  # GET /person_affiliations/new
  def new
    @person_affiliation = PersonAffiliation.new
  end

  # GET /person_affiliations/1/edit
  def edit
  end

  # POST /person_affiliations or /person_affiliations.json
  def create
    @person_affiliation = PersonAffiliation.new(person_affiliation_params)

    respond_to do |format|
      if @person_affiliation.save
        format.html { redirect_to @person_affiliation, notice: "Person affiliation was successfully created." }
        format.json { render :show, status: :created, location: @person_affiliation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person_affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /person_affiliations/1 or /person_affiliations/1.json
  def update
    respond_to do |format|
      if @person_affiliation.update(person_affiliation_params)
        format.html { redirect_to @person_affiliation, notice: "Person affiliation was successfully updated." }
        format.json { render :show, status: :ok, location: @person_affiliation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person_affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /person_affiliations/1 or /person_affiliations/1.json
  def destroy
    @person_affiliation.destroy
    respond_to do |format|
      format.html { redirect_to person_affiliations_url, notice: "Person affiliation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person_affiliation
      @person_affiliation = PersonAffiliation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_affiliation_params
      params.require(:person_affiliation).permit(:person_id, :affiliation_id)
    end
end

app/helpers/person_affiliations_helper.rb
module PersonAffiliationsHelper
end

app/views/person_affiliations/_form.html.erb
<%= form_with(model: person_affiliation) do |form| %>
  <% if person_affiliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person_affiliation.errors.count, "error") %> prohibited this person_affiliation from being saved:</h2>

      <ul>
        <% person_affiliation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.text_field :person_id %>
  </div>

  <div class="field">
    <%= form.label :affiliation_id %>
    <%= form.text_field :affiliation_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/person_affiliations/edit.html.erb
<h1>Editing Person Affiliation</h1>

<%= render 'form', person_affiliation: @person_affiliation %>

<%= link_to 'Show', @person_affiliation %> |
<%= link_to 'Back', person_affiliations_path %>

app/views/person_affiliations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Person Affiliations</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Affiliation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @person_affiliations.each do |person_affiliation| %>
      <tr>
        <td><%= person_affiliation.person_id %></td>
        <td><%= person_affiliation.affiliation_id %></td>
        <td><%= link_to 'Show', person_affiliation %></td>
        <td><%= link_to 'Edit', edit_person_affiliation_path(person_affiliation) %></td>
        <td><%= link_to 'Destroy', person_affiliation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person Affiliation', new_person_affiliation_path %>

app/views/person_affiliations/new.html.erb
<h1>New Person Affiliation</h1>

<%= render 'form', person_affiliation: @person_affiliation %>

<%= link_to 'Back', person_affiliations_path %>

app/views/person_affiliations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @person_affiliation.person_id %>
</p>

<p>
  <strong>Affiliation:</strong>
  <%= @person_affiliation.affiliation_id %>
</p>

<%= link_to 'Edit', edit_person_affiliation_path(@person_affiliation) %> |
<%= link_to 'Back', person_affiliations_path %>